### PR TITLE
feat: Add image generation api

### PR DESCRIPTION
**Pull request by SheepFromHeaven**
OpenAI just put image generation API Dall-E into open beta.

### CODE REVIEW

**Comment by SheepFromHeaven** [comment]
Do you know when this will be released? :)

**Comment by orhanerday** [comment]
I was in a meeting sorry :)

I just did [🚀](https://github.com/orhanerday/open-ai/releases/tag/2.3)

**Comment by orhanerday** [comment]
I was in a meeting sorry :)

 [I just did 🚀](https://github.com/orhanerday/open-ai/releases/tag/2.3)

**Comment by SheepFromHeaven** [comment]
Nothing to be sorry for 😆 you are doing noble deeds with your open source work 😄 

Thanks!

**Pull request merged**
